import type {
  FilterSectionConfig,
  Product,
  SortOptionItem,
  ThemeTokens,
} from "./types";

/* ---------------------------------- Tokens --------------------------------- */
export const C: ThemeTokens = {
  primary: "#835240",
  primaryLight: "#C98F7A",
  primaryDark: "#51291A",
  dark: "#3D2A1E",
  rose: "#B76E79",
  bg: "#FDF9F3",
  surface: "#F8F4EE",
  card: "#F2E8DD",
  heading: "#3B302A",
  body: "#51443F",
  muted: "#84746E",
  border: "#E6D9CF",
  success: "#4CAF50",
  warning: "#F59E0B",
  error: "#BA1A1A",
};

/* ------------------------------ Filter Schema ------------------------------
   This shape is the ONLY contract the UI depends on — swap in real API data
   with zero component changes.
----------------------------------------------------------------------------*/
export const FILTERS: FilterSectionConfig[] = [
  {
    id: "category",
    title: "Category",
    type: "radio",
    options: [
      { id: "kurtis", label: "Kurtis", value: "kurtis", count: 398 },
      { id: "kurtas", label: "Kurtas", value: "kurtas", count: 371 },
      { id: "dresses", label: "Dresses", value: "dresses", count: 129 },
      { id: "sets", label: "Co-ord Sets", value: "sets", count: 84 },
      { id: "sarees", label: "Sarees", value: "sarees", count: 212 },
    ],
  },
  {
    id: "brand",
    title: "Brand",
    type: "checkbox",
    searchable: true,
    options: [
      {
        id: "vyraaa-house",
        label: "Vyraaa House",
        value: "vyraaa-house",
        count: 156,
      },
      { id: "anouk-r", label: "Anouk Rustic", value: "anouk-r", count: 24 },
      { id: "roshni", label: "Roshni", value: "roshni", count: 76 },
      { id: "julee", label: "Julee", value: "julee", count: 41 },
      { id: "monique", label: "Monique", value: "monique", count: 19 },
    ],
  },
  {
    id: "price",
    title: "Price",
    type: "range",
    min: 499,
    max: 9999,
    step: 100,
    unit: "₹",
    quickValues: [499, 999, 1999],
  },
  {
    id: "discount",
    title: "Discount",
    type: "checkbox",
    options: [
      { id: "d10", label: "10% and above", value: "10", count: 612 },
      { id: "d20", label: "20% and above", value: "20", count: 480 },
      { id: "d30", label: "30% and above", value: "30", count: 355 },
      { id: "d40", label: "40% and above", value: "40", count: 210 },
      { id: "d50", label: "50% and above", value: "50", count: 132 },
      { id: "d70", label: "70% and above", value: "70", count: 44 },
    ],
  },
  {
    id: "rating",
    title: "Customer Rating",
    type: "radio",
    options: [
      { id: "r4", label: "4★ & above", value: "4", count: 588 },
      { id: "r3", label: "3★ & above", value: "3", count: 891 },
      { id: "r2", label: "2★ & above", value: "2", count: 1023 },
    ],
  },
  {
    id: "size",
    title: "Size",
    type: "size",
    options: ["XS", "S", "M", "L", "XL", "XXL"].map((s) => ({
      id: s,
      label: s,
      value: s,
    })),
  },
  {
    id: "color",
    title: "Colour",
    type: "color",
    options: [
      { id: "white", label: "White", value: "white", swatch: "#FFFFFF" },
      { id: "ivory", label: "Ivory", value: "ivory", swatch: "#F4EDE1" },
      { id: "black", label: "Black", value: "black", swatch: "#221B17" },
      { id: "beige", label: "Beige", value: "beige", swatch: "#D8C3A5" },
      { id: "gold", label: "Gold", value: "gold", swatch: "#C9A24B" },
      {
        id: "rose-gold",
        label: "Rose Gold",
        value: "rose-gold",
        swatch: "#B76E79",
      },
      { id: "olive", label: "Olive", value: "olive", swatch: "#6E7256" },
      { id: "wine", label: "Wine", value: "wine", swatch: "#5E2129" },
      { id: "pink", label: "Pink", value: "pink", swatch: "#E7ADB8" },
      { id: "blue", label: "Blue", value: "blue", swatch: "#3E5C76" },
      { id: "green", label: "Green", value: "green", swatch: "#3F5B45" },
      { id: "mustard", label: "Mustard", value: "mustard", swatch: "#C99A2E" },
    ],
  },
  {
    id: "fabric",
    title: "Fabric",
    type: "checkbox",
    options: [
      "Cotton",
      "Silk",
      "Linen",
      "Rayon",
      "Muslin",
      "Organza",
      "Georgette",
    ].map((f) => ({
      id: f.toLowerCase(),
      label: f,
      value: f.toLowerCase(),
      count: Math.floor(Math.random() * 200) + 20,
    })),
  },
  {
    id: "sleeve",
    title: "Sleeve",
    type: "checkbox",
    options: ["Half", "Full", "3/4", "Sleeveless"].map((s) => ({
      id: s,
      label: s,
      value: s,
    })),
  },
  {
    id: "neck",
    title: "Neck",
    type: "checkbox",
    options: ["Round", "V Neck", "Boat Neck", "Mandarin", "Square"].map(
      (n) => ({ id: n, label: n, value: n }),
    ),
  },
  {
    id: "occasion",
    title: "Occasion",
    type: "checkbox",
    options: [
      "Wedding",
      "Festive",
      "Office",
      "Party",
      "Vacation",
      "Daily Wear",
    ].map((o) => ({ id: o, label: o, value: o })),
  },
  {
    id: "pattern",
    title: "Pattern",
    type: "checkbox",
    options: ["Solid", "Printed", "Floral", "Embroidered", "Ethnic Motif"].map(
      (p) => ({ id: p, label: p, value: p }),
    ),
  },
  {
    id: "availability",
    title: "Availability",
    type: "toggle",
    options: [
      { id: "in-stock", label: "In Stock", value: "in-stock" },
      { id: "express", label: "Express Delivery", value: "express" },
      { id: "cod", label: "Cash on Delivery", value: "cod" },
    ],
  },
];

export const CATEGORY_CHIPS: string[] = [
  "New",
  "Festive",
  "Office",
  "Casual",
  "Cotton",
  "Silk",
  "Designer",
  "Premium",
  "Best Seller",
  "Trending",
];

export const SORT_OPTIONS: SortOptionItem[] = [
  { id: "recommended", label: "Recommended" },
  { id: "newest", label: "Newest" },
  { id: "popularity", label: "Popularity" },
  { id: "trending", label: "Trending" },
  { id: "price-asc", label: "Price: Low to High" },
  { id: "price-desc", label: "Price: High to Low" },
  { id: "discount", label: "Discount" },
  { id: "rating", label: "Customer Rating" },
  { id: "editors", label: "Editor's Picks" },
];

const BASE_PRODUCTS: Product[] = [
  {
    id: "p1",
    brand: "Vyraaa House",
    name: "Anahita Hand-Embroidered Kurti",
    img: "https://picsum.photos/seed/vyr1a/600/750",
    img2: "https://picsum.photos/seed/vyr1b/600/750",
    rating: 4.6,
    reviews: 128,
    price: 3499,
    mrp: 5999,
    delivery: "Jul 9",
    badges: ["New"],
  },
  {
    id: "p2",
    brand: "Roshni",
    name: "Ivory Muslin Ethnic Motif Kurti",
    img: "https://picsum.photos/seed/vyr2a/600/750",
    img2: "https://picsum.photos/seed/vyr2b/600/750",
    rating: 4.4,
    reviews: 76,
    price: 2199,
    mrp: 3999,
    delivery: "Jul 8",
    badges: ["Best Seller"],
  },
  {
    id: "p3",
    brand: "Vyraaa House",
    name: "Wine Silk Organza Co-ord Set",
    img: "https://picsum.photos/seed/vyr3a/600/750",
    img2: "https://picsum.photos/seed/vyr3b/600/750",
    rating: 4.8,
    reviews: 214,
    price: 6799,
    mrp: 9999,
    delivery: "Jul 10",
    badges: ["Premium", "Limited Stock"],
  },
  {
    id: "p4",
    brand: "Julee",
    name: "Rose Gold Georgette Anarkali",
    img: "https://picsum.photos/seed/vyr4a/600/750",
    img2: "https://picsum.photos/seed/vyr4b/600/750",
    rating: 4.3,
    reviews: 52,
    price: 4299,
    mrp: 6499,
    delivery: "Jul 7",
    badges: [],
  },
  {
    id: "p5",
    brand: "Monique",
    name: "Olive Linen Straight Kurti",
    img: "https://picsum.photos/seed/vyr5a/600/750",
    img2: "https://picsum.photos/seed/vyr5b/600/750",
    rating: 4.1,
    reviews: 34,
    price: 1899,
    mrp: 2999,
    delivery: "Jul 9",
    badges: ["Only Few Left"],
  },
  {
    id: "p6",
    brand: "Vyraaa House",
    name: "Beige Cotton Printed Kurti",
    img: "https://picsum.photos/seed/vyr6a/600/750",
    img2: "https://picsum.photos/seed/vyr6b/600/750",
    rating: 4.5,
    reviews: 190,
    price: 1599,
    mrp: 2599,
    delivery: "Jul 6",
    badges: ["Best Seller"],
  },
  {
    id: "p7",
    brand: "Anouk Rustic",
    name: "Mustard Floral Printed Tunic",
    img: "https://picsum.photos/seed/vyr7a/600/750",
    img2: "https://picsum.photos/seed/vyr7b/600/750",
    rating: 4.4,
    reviews: 402,
    price: 1381,
    mrp: 3299,
    delivery: "Jul 6",
    badges: ["New"],
  },
  {
    id: "p8",
    brand: "Vyraaa House",
    name: "Pink Embroidered Festive Kurti",
    img: "https://picsum.photos/seed/vyr8a/600/750",
    img2: "https://picsum.photos/seed/vyr8b/600/750",
    rating: 4.7,
    reviews: 98,
    price: 3899,
    mrp: 5499,
    delivery: "Jul 8",
    badges: ["Premium"],
  },
];

// Original file repeated the same 8 products twice to pad the demo grid —
// preserved as-is to keep behaviour identical.
export const PRODUCTS: Product[] = [...BASE_PRODUCTS, ...BASE_PRODUCTS];
