import {
  womenPerfume,
  mensPerfume,
  cosmetics,
  bag,
  watch,
  wallets,
  jewellery,
  scarves,
} from "../../../../assets/assets";

import type { Product } from "./search";

export const PRODUCTS: Product[] = [
  {
    id: "p1",
    name: "Luxore Eau De Parfum",
    slug: "luxore-eau-de-parfum",
    image: womenPerfume,
    currentPrice: 799,
    originalPrice: 1299,
    category: "Women's Perfume",
    tags: ["perfume", "women", "floral", "luxury"],
  },
  {
    id: "p2",
    name: "Royal Oud Intense",
    slug: "royal-oud-intense",
    image: mensPerfume,
    currentPrice: 1499,
    originalPrice: 1999,
    category: "Men's Perfume",
    tags: ["oud", "woody", "luxury", "men"],
  },
  {
    id: "p3",
    name: "Velvet Rose Mist",
    slug: "velvet-rose-mist",
    image: womenPerfume,
    currentPrice: 999,
    originalPrice: 1499,
    category: "Women's Perfume",
    tags: ["rose", "floral", "premium"],
  },
  {
    id: "p4",
    name: "Ocean Breeze Cologne",
    slug: "ocean-breeze-cologne",
    image: mensPerfume,
    currentPrice: 899,
    originalPrice: 1299,
    category: "Men's Perfume",
    tags: ["fresh", "aquatic", "daily"],
  },
  {
    id: "p5",
    name: "Luxury Makeup Kit",
    slug: "luxury-makeup-kit",
    image: cosmetics,
    currentPrice: 1899,
    originalPrice: 2499,
    category: "Cosmetics",
    tags: ["makeup", "beauty", "kit"],
  },
  {
    id: "p6",
    name: "Glow Essentials Set",
    slug: "glow-essentials-set",
    image: cosmetics,
    currentPrice: 1299,
    originalPrice: 1699,
    category: "Cosmetics",
    tags: ["skincare", "beauty", "women"],
  },
  {
    id: "p7",
    name: "Classic Leather Handbag",
    slug: "classic-leather-handbag",
    image: bag,
    currentPrice: 2299,
    originalPrice: 2999,
    category: "Bags",
    tags: ["handbag", "leather", "fashion"],
  },
  {
    id: "p8",
    name: "Premium Travel Tote",
    slug: "premium-travel-tote",
    image: bag,
    currentPrice: 1799,
    originalPrice: 2399,
    category: "Bags",
    tags: ["tote", "travel", "bag"],
  },
  {
    id: "p9",
    name: "Chrono Steel Watch",
    slug: "chrono-steel-watch",
    image: watch,
    currentPrice: 3499,
    originalPrice: 4499,
    category: "Watches",
    tags: ["watch", "steel", "men"],
  },
  {
    id: "p10",
    name: "Rose Gold Women's Watch",
    slug: "rose-gold-watch",
    image: watch,
    currentPrice: 2999,
    originalPrice: 3799,
    category: "Watches",
    tags: ["watch", "women", "rose-gold"],
  },
  {
    id: "p11",
    name: "Leather Wallet",
    slug: "leather-wallet",
    image: wallets,
    currentPrice: 899,
    originalPrice: 1299,
    category: "Wallets",
    tags: ["wallet", "leather", "accessories"],
  },
  {
    id: "p12",
    name: "Premium Card Holder",
    slug: "premium-card-holder",
    image: wallets,
    currentPrice: 699,
    originalPrice: 999,
    category: "Wallets",
    tags: ["wallet", "card", "minimal"],
  },
  {
    id: "p13",
    name: "Diamond Elegance Necklace",
    slug: "diamond-elegance-necklace",
    image: jewellery,
    currentPrice: 3999,
    originalPrice: 4999,
    category: "Jewellery",
    tags: ["necklace", "diamond", "women"],
  },
  {
    id: "p14",
    name: "Pearl Drop Earrings",
    slug: "pearl-drop-earrings",
    image: jewellery,
    currentPrice: 1599,
    originalPrice: 2199,
    category: "Jewellery",
    tags: ["earrings", "pearl", "fashion"],
  },
  {
    id: "p15",
    name: "Silk Designer Scarf",
    slug: "silk-designer-scarf",
    image: scarves,
    currentPrice: 1199,
    originalPrice: 1599,
    category: "Scarves",
    tags: ["scarf", "silk", "women"],
  },
  {
    id: "p16",
    name: "Winter Wool Scarf",
    slug: "winter-wool-scarf",
    image: scarves,
    currentPrice: 899,
    originalPrice: 1299,
    category: "Scarves",
    tags: ["winter", "wool", "fashion"],
  },
];

export function getAllProducts(): Product[] {
  return PRODUCTS;
}