import type { ProductItem } from "./types";

export const dummyProducts: ProductItem[] = [
  {
    _id: "1",
    title: "Men Typography Polo Neck Cotton Blend Multicolor T-Shirt",
    description: "",
    image:
      "https://macreelinfosoft-bucket.s3.ap-south-1.amazonaws.com/Vyraaa-Admin-Images/1784205523374.jpeg",
    subImages: [],
    color: "Snow",
    category: "Clothes",
    subCategory: "T-Shirts",
    brand: "Nike",
    gender: "Men",
    sizeType: "Alpha",
    averageRating: 0,
    price: [
      {
        _id: "1",
        size: "XS",
        amount: 380,
        markupPrice: 400,
        discount: 5,
        skuCode: "XS-T50",
        isAvailable: true,
        isFewLeft: true,
      },
      {
        _id: "2",
        size: "S",
        amount: 456,
        markupPrice: 480,
        discount: 5,
        skuCode: "S-T50",
        isAvailable: true,
        isFewLeft: false,
      },
      {
        _id: "3",
        size: "L",
        amount: 332,
        markupPrice: 350,
        discount: 5,
        skuCode: "L-T50",
        isAvailable: true,
        isFewLeft: true,
      },
    ],
  },

  {
    _id: "2",
    title: "Women Khaki Handbag",
    description: "",
    image:
      "https://macreelinfosoft-bucket.s3.ap-south-1.amazonaws.com/Vyraaa-Admin-Images/1784206613915.jpeg",
    subImages: [],
    color: "Khaki",
    category: "Bags",
    subCategory: "Handbags",
    brand: "Lavie",
    gender: "Women",
    sizeType: "Inches",
    averageRating: 0,
    price: [
      {
        _id: "1",
        size: "9",
        amount: 920,
        markupPrice: 1000,
        discount: 8,
        skuCode: "BAG-9",
        isAvailable: true,
        isFewLeft: false,
      },
    ],
  },

  {
    _id: "3",
    title: "Velcro Walking Shoes For Boys & Girls",
    description: "",
    image:
      "https://macreelinfosoft-bucket.s3.ap-south-1.amazonaws.com/Vyraaa-Admin-Images/1784208243761.jpeg",
    subImages: [],
    color: "Coal",
    category: "Shoes",
    subCategory: "Sports Shoes",
    brand: "Campus",
    gender: "Unisex",
    sizeType: "Numeric",
    averageRating: 0,
    price: [
      {
        _id: "1",
        size: "7",
        amount: 350,
        markupPrice: 1000,
        discount: 65,
        skuCode: "SHOE-7",
        isAvailable: false,
        isFewLeft: false,
      },
    ],
  },

  {
    _id: "4",
    title: "Men Printed Round Neck Polyester Black T-Shirt",
    description: "",
    image:
      "https://macreelinfosoft-bucket.s3.ap-south-1.amazonaws.com/Vyraaa-Admin-Images/1784206004512.jpeg",
    subImages: [],
    color: "Sky Blue",
    category: "Clothes",
    subCategory: "T-Shirts",
    brand: "Adidas",
    gender: "Men",
    sizeType: "Alpha",
    averageRating: 0,
    price: [
      {
        _id: "1",
        size: "XS",
        amount: 2500,
        markupPrice: 5000,
        discount: 50,
        skuCode: "TS-1",
        isAvailable: true,
        isFewLeft: false,
      },
    ],
  },
];
